<a href="https://colab.research.google.com/github/poojashreeNS/Assignments/blob/main/singleLink-table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [166]:
import math as math
import numpy as np

X = [(2, 2), (2, 6), (3, 7), (5, 2), (5, 5), (5, 8), (6, 6), (7, 3), (8, 4), (10, 6), (12, 8)]
Matrix = [[0 for x in range(len(X))] for y in range(len(X))]
distance = 0

for i in range(len(X)):
  for j in range(len(X)):
    x1 = X[i][0]
    x2 = X[j][0]
    y1 = X[i][1]
    y2 = X[j][1]
    distance = math.sqrt((x1 - x2)**2 + (y1 - y2)**2)
    Matrix[i][j] = round(distance, 2)

In [167]:
for row in Matrix:
    print(*row, sep='\t')
    print("\t")

0.0	4.0	5.1	3.0	4.24	6.71	5.66	5.1	6.32	8.94	11.66
	
4.0	0.0	1.41	5.0	3.16	3.61	4.0	5.83	6.32	8.0	10.2
	
5.1	1.41	0.0	5.39	2.83	2.24	3.16	5.66	5.83	7.07	9.06
	
3.0	5.0	5.39	0.0	3.0	6.0	4.12	2.24	3.61	6.4	9.22
	
4.24	3.16	2.83	3.0	0.0	3.0	1.41	2.83	3.16	5.1	7.62
	
6.71	3.61	2.24	6.0	3.0	0.0	2.24	5.39	5.0	5.39	7.0
	
5.66	4.0	3.16	4.12	1.41	2.24	0.0	3.16	2.83	4.0	6.32
	
5.1	5.83	5.66	2.24	2.83	5.39	3.16	0.0	1.41	4.24	7.07
	
6.32	6.32	5.83	3.61	3.16	5.0	2.83	1.41	0.0	2.83	5.66
	
8.94	8.0	7.07	6.4	5.1	5.39	4.0	4.24	2.83	0.0	2.83
	
11.66	10.2	9.06	9.22	7.62	7.0	6.32	7.07	5.66	2.83	0.0
	


In [185]:
Matrix = np.array(Matrix)

index = np.where(Matrix == np.min(Matrix[Matrix > 0]))
print(index)
print(index[0][0], index[1][0])

row1 = Matrix[index[0][0]]
row2 = Matrix[index[1][0]]
print(row1)
print(row2)

matrix_row_new = np.minimum(row1, row2)
print(matrix_row_new)
matrix_row_new = np.delete(matrix_row_new, [index[0][0], index[1][0]], 0)
#print(matrix_row_new)

matrix_del_col = np.delete(Matrix, [index[0][0], index[1][0]], 1)
#print(matrix_del_col)

matrix_del_row = np.delete(matrix_del_col, [index[0][0], index[1][0]], 0)
#print(matrix_del_row)

arr = np.insert(matrix_del_row,matrix_del_row.shape[0],[matrix_row_new],axis= 0)
#print(arr)

matrix_row_new = np.append(matrix_row_new, [0])
print(matrix_row_new)

Matrix = np.insert(arr,matrix_del_row.shape[0],[matrix_row_new],axis= 1)

(array([1, 2]), array([2, 1]))
1 2
[8.94 0.   2.83]
[3.   2.83 0.  ]
[3. 0. 0.]
[3. 0.]


In [186]:
print("____________Next step output_________")
print(Matrix)
print("___________Merged Indices____________")
print(index[0][0], index[1][0])
print("_____________________________________")

____________Next step output_________
[[0. 3.]
 [3. 0.]]
___________Merged Indices____________
1 2
_____________________________________
